import { Jua, Cairo } from "next/font/google";
import "./_globals/globals.scss";
import Navbar from "./_components/common/Navbar/Navbar";
// import localFont from 'next/font/local'
 
// const myFont = localFont({
//   src: './_fonts/JejuMyeongjo.woff2',
// });
 
const jua = Jua({
  variable: "--font-jua",
  weight: '400',
  subsets: ["latin"],
});

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${jua.className} ${cairo.className}`}>
      <body><Navbar />
      {children}</body>
    </html>
  )
}
